### ISSUE TITLE
Unit missing in olevhalf in CMIP6_coordinate.json

### ISSUE THREAD

**Issue by treerink** [PCMDI/cmip6-cmor-tables#237] opened 2019-03-06 10:32 UTC
Hi,

We wonder whether the unit of `olevhalf`in `CMIP6_coordinate.json`  should not be "`m`", currently it is empty. See (in current version) line 1032 in:
`https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json`

Currently we have the following trouble while cmorising `zhalfo:`
`````
! Error: axis 4 (olevhalf, table: Omon): cmor and user units are
! incompatible:  and m
`````
However, if we take unit "`m`" in `olevhalf`, then `zhalfo` is cmorising well.

Regards,
Thomas

**Comment by taylor13** [comment] 2019-03-07 19:15
Hi Thomas,
Thank you for uncovering this bug.  I am sorry for the trouble you have gone to diagnosing it.  We need to modify the coordinates.json file so that it includes "depth_coord_half".   It will have the correct standard_name, units, etc. for models that use depth as the vertical coordinate (or that are regridded to a depth coordinate.    If you use a different coordinate for your CMIP6 output, please let us know.

More generally, I have reviewed the CMIP6_coordinate.json table and find a number of problems with the handling of the vertical coordinates.  Here is a summary of the problems/issues which need to be addressed:

1. Add dimension 
```
"depth_coord_half": {
            "standard_name": "depth", 
            "units": "m", 
            "axis": "Z", 
            "long_name": "ocean depth coordinate", 
            "climatology": "", 
            "formula": "", 
            "must_have_bounds": "no", 
            "out_name": "lev", 
            "positive": "down", 
            "requested": "", 
            "requested_bounds": "", 
            "stored_direction": "increasing", 
            "tolerance": "", 
            "type": "", 
            "valid_max": "12000.0", 
            "valid_min": "0.0", 
            "value": "", 
            "z_bounds_factors": "", 
            "z_factors": "", 
            "bounds_values": "", 
            "generic_level_name": "olevhalf"
},
``` 
This will not work, however, unless CMOR3 interprets generic_level_name="olevhalf" similarly to "alevhalf".  This needs to be confirmed.

2.  Remove dimension "olevhalf" because it isn't needed.

3.   Also consider removing hybrid_height and smooth_level coordinates because they won't work without adding orog, zsurf1 and zsurf2 to the following CMOR CMIP6 tables:  6hrlev, AERmon, Amon, CF3hr, CFday, CFmon, CFsubhr, E3hrPt, E6hrZ, Emon, Esubhr.
4. The following dimensions currently have units = "" but should be defined as follows:
natural_log_pressure units="Pa"
natural_log_pressure_half units="Pa"

5.  Griffies et al, (https://www.geosci-model-dev.net/9/3231/2016/gmd-9-3231-2016.pdf) request ocean output be provided using one of the following coordinates: z (geopotential), z*(stretched depth), p (pressure), or p* (stretched pressure).  I think the CF convention isn't aware of z* or p*, and the cmor table hasn't yet been generalized to handle p, so z is the only option with CMOR.  We can augment CMOR and its table to handle p, z*, and p*, but I want to determine whether or not this is a priority.

**Comment by treerink** [comment] 2019-03-08 08:48
Ok thank you for your reply. We indeed use a simple depth coordinate so that's alright. So we wait your update on including `depth_coord_half` (and the removal of `olevhalf`). Would this update come rather soon, like within a week or so?

I believe the rest of your points are not directly related to our current issue.

Regards,
Thomas

**Comment by matthew-mizielinski** [comment] 2019-03-08 15:15
I've mentioned this in direct e-mail to @taylor13 , but for completeness I note here that the `hybrid_height` functionality in CMOR works fine for us; we end up with the `orog` variable in the each output file along with `a` and `b` coefficients and associated bounds. If useful I can dig into how this is supplied to CMOR, but it is working.

**Comment by taylor13** [comment] 2019-03-08 16:52
thanks @matthew-mizielinski for that information.  I'm glad CMOR can write `orog` along with the variable of interest in each file, as it should. I was afraid it didn't know about that "zfactor" but I was wrong.  That's good.  I've edited point 3 in my long post above so that I no longer suggest removing `hybrid_height`.

**Comment by taylor13** [comment] 2019-03-08 17:00
@mauzey1 -- @treerink has noticed a coordinate is missing from the CMIP6_coordinate.json file, and this is holding up their production.  Could we quickly add the `depth_coord_half` coordinate defined in  https://github.com/PCMDI/cmip6-cmor-tables/issues/237#issuecomment-470656858 and make it available?  Also we should remove the `olevhalf` coordinate as it shouldn't be needed.  Do we have a "nightly" version of the tables or would we need to make a new release?

**Comment by mauzey1** [comment] 2019-03-08 19:31
@taylor13 I have made a pull requests that adds `depth_coord_half` to CMIP6_coordinate.json.  The dimension `olevhalf` appears to come from the data request.
```
<item altLabel="lev" axis="Z" bounds="no" boundsValues="" coords="" description="generic ocean model vertical coordinate (nondimensional or dimensional)" direction="" isGrid="" isIndex="ok" label="olevhalf" positive="down" requested="" tables="" title="ocean model half levels" tolRequested="" type="double" uid="dim:olevhalf" units="" value=""></item>
```
When you say "nightly" version, do you mean the latest changes in the master branch of this repo?

**Comment by taylor13** [comment] 2019-03-08 23:49
Actually, I don't know what I mean.  If, once you've merged the new coordinate.json file, @treerink can access the table at https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables (or somewhere else you point us to), then we won't be holding up production.
thanks.

**Comment by mauzey1** [comment] 2019-03-09 00:54
The changes to add `depth_coord_half` have been merged and are now available at https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables

**Comment by treerink** [comment] 2019-03-17 13:14
Thanks for adding `depth_coord_half` to `CMIP6_coordinate.json`. So closing issue.

Regards,
Thomas

**Comment by taylor13** [comment] 2019-03-18 15:16
I just recalled that in order to treat "generic" vertical coordinates correctly, I think the CMOR tables referring to olevhalf need to include at the top ``"generic_levels": "olevel", ``.  Perhaps because depth_coord_half can be handled like a regular coordinate, it isn't needed in this case.  But I don't really see why it should.  How does it know that depth_coord_half can be used to satisfy ``olevhalf``?

Anyway, I *think* we need to modify the ``generic_levels`` list in tables Omon.json and Oclim.json to read:
```
"generic_levels": "olevel olevhalf", 
```
Please confirm before changing.  Perhaps @treerink can say whether his code works without this change?

**Comment by treerink** [comment] 2019-03-20 15:49
No we had not tested it yet.

With the updated cmor tables, we get the following error now:
`````
C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable 'zhalfo' (table Omon) with axis id 'depth_coord_half' which is not part of this variable according to your table,
 it says: ( time olevhalf latitude longitude )
!
!!!!!!!!!!!!!!!!!!!!!!!!!
`````
So I guess that confirms your hypothesis?

**Comment by taylor13** [comment] 2019-03-20 16:06
Yes, I  suspect it does.  @mauzey1 : how should we proceed?  Should we just add ``olevhalf`` to the ``generic_levels`` in tables Omon.json and Oclim.json, and then ask @treerink to retry?  Or is there some local testing we should do to confirm that this is the problem?

**Comment by mauzey1** [comment] 2019-03-20 16:59
I tried testing `zhalfo` using the following code.
```
import cmor
import numpy


def main():

    cmor.setup(inpath='Tables',
               netcdf_file_action=cmor.CMOR_REPLACE_3)
    cmor.dataset_json("Test/CMOR_input_example.json")

    table = 'CMIP6_Omon.json'
    cmor.load_table(table)
    axes = [{'table_entry': 'time',
             'units': 'days since 1850-01-01 00:00:00',
             'coord_vals': [15.5, 45, ],
             'cell_bounds':[[0, 31], [31, 62]]
             },
            {'table_entry': 'depth_coord_half',
             'units': 'm',
             'coord_vals': [5000., 3000., 2000., 1000.]},
            {'table_entry': 'latitude',
             'units': 'degrees_north',
             'coord_vals': [0],
             'cell_bounds': [-1, 1]},
            {'table_entry': 'longitude',
             'units': 'degrees_east',
             'coord_vals': [90],
             'cell_bounds': [89, 91]},
            ]

    axis_ids = list()
    for axis in axes:
        print 'doing:', axis
        axis_id = cmor.axis(**axis)
        axis_ids.append(axis_id)

    for var, units, value in (('zhalfo', 'm', 274.),):
        values = numpy.ones(map(lambda x: len(x["coord_vals"]), axes)) * value
        values = values.astype("f")
        varid = cmor.variable(var,
                              units,
                              axis_ids,
                              history='variable history',
                              missing_value=-99
                              )
        cmor.write(varid, values)

    cmor.close()


if __name__ == '__main__':

    main()
```
This generated the same error that @treerink posted.  However, changing the `generic_levels` in `CMIP6_Omon.json` to `"olevel olevhalf"` didn't get rid of the error.

**Comment by taylor13** [comment] 2019-03-20 18:16
This is puzzling.  I guess something must be going wrong in the code in lines 1570-1618 of ``cmor_variables.c`` . Perhaps @doutriaux1  can help debug.  Why isn't it recognizing ``depth_coord_half`` as a valid option for the generic vertical coordinate ``olevhalf`` ?

**Comment by taylor13** [comment] 2019-03-20 18:21
By the way, thanks very much, @mauzey1 for devising the test!  I wonder if trying to write a variable defined on ``olevel``  (e.g., ``dmso``) using the ``depth_coord`` works?  It's supposed to, but I don't see any difference between that and a case with olevhalf and depth_coord_half.

**Comment by taylor13** [comment] 2019-03-21 23:13
I think I've found at least part of the solution:  We need to add a line to the cmor.h file:
```
#define DIMENSION_OLEVEL_HALF "olevhalf"
```
(probably placed after line 256).

And in cmor_variables.c following lines 1984-1988: 
```
            if (n == -1) {
                j = strcmp(DIMENSION_ZLEVEL, dim);
                j *= strcmp(DIMENSION_ALEVEL, dim);
                j *= strcmp(DIMENSION_ALEVEL_HALF, dim);
                j *= strcmp(DIMENSION_OLEVEL, dim);
```
we need to add another line that includes ``DIMENSION_OLEVEL_HALF``.

**Comment by mauzey1** [comment] 2019-03-26 19:07
@taylor13 The bug with `olevhalf` was being caused by its inclusion in `CMIP6_coordinate.json`.

https://github.com/PCMDI/cmor/blob/19d6f632dacec5bf43ddcb950c1f1bd1291e8193/Src/cmor_variables.c#L1976-L2023

In this section of code, lines 1977-1982 will find the dimension `olevhalf` in `CMIP6_coordinate.json`.  This would cause it to skip the code in lines 1984-2021, preventing the variable `var->dimensions[var->ndims]` from being set to -2 and `var->generic_level_name` from being set to `olevhalf`.  This leads to errors in this section: https://github.com/PCMDI/cmor/blob/19d6f632dacec5bf43ddcb950c1f1bd1291e8193/Src/cmor_variables.c#L1571-L1617

I have made pull requests for PCMDI/xml-cmor3-database, PCMDI/cmip6-cmor-tabels, and PCMDI/cmor that add `olevhalf` to the generic_levels of `CMIP6_Omon.json` and remove it from `CMIP6_coordinate.json`.  I also added `DIMENSION_OLEVEL_HALF` to CMOR and added it to the section of code mentioned in https://github.com/PCMDI/cmip6-cmor-tables/issues/237#issuecomment-475437642.

**Comment by treerink** [comment] 2019-04-02 14:51
Hi, 

It looks you are (close) at a solution. But I tried updating the tables and I get still the same error, so that means these changes didn't make it so far to the repository. Is this coming soon?

**Comment by taylor13** [comment] 2019-05-09 19:56
@mauzey1 What is the status of this?

**Comment by mauzey1** [comment] 2019-05-09 20:18
@taylor13 This issue should be fixed by https://github.com/PCMDI/cmip6-cmor-tables/pull/241.  I think we can close this issue.

**Closed** 2019-05-09 21:24 UTC

**Comment by treerink** [comment] 2019-05-16 15:57
Thanks, issue is indeed solved with the latest cmor table update.
